apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.canvasPort }}
      targetPort: canvas
      protocol: TCP
      name: canvas
  selector:
    {{- include "openclaw.selectorLabels" . | nindent 4 }}
